name = "Atypical ML"
description = "Abnormal musings and thoughts of the world."
tags = ["blog", "clean", "customizable", "dark", "highlighting", "light", "minimal", "monochromatic", "multilingual", "personal", "responsive", "simple", "technical"]
features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.30

[author]
  name = "Kunal Sharda"


